import type { Metadata } from "next";
import "../globals.css";
import Button, { buttonVariants } from "@/components/ui/Button";
import { cn } from "@/lib/utils";
import Link from "next/link";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  if (session) {
    redirect("/dashboard");
  }
  return (
    <main className="bg-white flex flex-col items-start justify-center ">
      <Link
        href="/"
        className={cn(buttonVariants(), "absolute left-4  md:left-12 top-8")}
      >
        Back home
      </Link>
      {children}
    </main>
  );
}
